#PROGRAMMER: ALEX DANILUSHKIN
#Z-ID:       Z1809166
#CLASS:      CSCI 480-02
#DUE DATE:   03/24/2019
#ASSIGNMENT: 5

assign5: assign5.cc
	g++ -pthread -Wall -g -std=c++11 assign5.cc -o assign5

clean:
	rm assign5
