#PROGRAMMER: ALEX DANILUSHKIN
#Z-ID: z1809166
#CLASS AND SECTION: 480-1
#TA: JOSHUA BOLEY
#DUE DATE: JANUARY 25, 2019
#
assign1 : assign1.o
	g++ -Wall -o assign1 assign1.o
assign1.o : assign1.c
	g++ -Wall -c assign1.c
Clean:
	-rm *.o
	-rm assign1

