#PROGRAMMER: ALEX DANILUSHKIN
#Z-ID: z1809166
#CLASS AND SECTION: 480-1
#TA: JOSHUA BOLEY
#DUE DATE: FEBRUARY 8TH, 2019
#
assign2 : assign1.o
	g++ -Wall -o assign2 assign2.o
assign1.o : assign2.c
	g++ -Wall -c assign2.c
clean:
	-rm *.o
	-rm assign2


